services:
  api:
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
 
