"""add payments table

Revision ID: 034e54cfcdfe
Revises: 84aa5e338c55
Create Date: 2025-09-02 11:18:13.931429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034e54cfcdfe'
down_revision: Union[str, Sequence[str], None] = '84aa5e338c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=False)
    # ### end Alembic commands ###
