"""Your message

Revision ID: 1d0e7cb79175
Revises: 82bda91be124
Create Date: 2025-09-03 07:27:20.135241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0e7cb79175'
down_revision: Union[str, Sequence[str], None] = '82bda91be124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.create_index('ix_users_phone_e164', 'users', ['phone_e164'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_e164', table_name='users')
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=True)
    # ### end Alembic commands ###
